export { useDoctorDashboard } from './useDashboard';
export { useDoctorAppointments, useDoctorAppointment, useUpdateAppointmentStatus } from './useAppointments';
export { useEncounterByAppointment, useCreateEncounter, useUpdateEncounter } from './useEncounters';
export { usePrescriptionsByEncounter, usePrescriptionsByPatient, useCreatePrescription } from './usePrescriptions';
export { useDoctorPatients, useDoctorPatient, useCreateDoctorPatient, useUpdateDoctorPatient, useDeleteDoctorPatient, useAssignPatients, useMyPatients, useUnassignPatient } from './usePatients';
export { useDoctorBilling } from './useBilling';
export { useDoctorDeviceReports } from './useDeviceReports';
export { useFamilyByPatient } from './useFamily';
export { useWhatsAppConfig, useUpdateWhatsAppConfig } from './useWhatsApp';
export { useMarketingReviews } from './useMarketing';
export { useDoctorProfile, useDoctorProfileCompletion, useSaveDoctorProfile, useDeleteDoctorProfile, useUploadFile, useAutoSaveDoctorProfile } from './useDoctorProfile';
export { useEmergencyContacts, useAddEmergencyContact, useUpdateEmergencyContact, useDeleteEmergencyContact } from './useEmergencyContacts';
